<?php
define('WP_CACHE', true);
define('FORCE_SSL_ADMIN', true);
define('WP_HOME','https://twojastrona.pl');
define('WP_SITEURL','https://twojastrona.pl');
define('DB_NAME','nazwa bazy danych');
define('DB_USER','użytkownik bazy danych');
define('DB_PASSWORD','hasł bazy danych');
define('DB_HOST','codeasy.mysql.dhosting.pl:3306');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
$table_prefix = 'prefix_';
define('AUTH_KEY',         '');
define('SECURE_AUTH_KEY',  'Twoje indywidualne klucze wordpress API');
define('LOGGED_IN_KEY',    'Twoje indywidualne klucze wordpress API');
define('NONCE_KEY',        'Twoje indywidualne klucze wordpress API');
define('AUTH_SALT',        'Twoje indywidualne klucze wordpress API');
define('SECURE_AUTH_SALT', 'Twoje indywidualne klucze wordpress API');
define('LOGGED_IN_SALT',   'Twoje indywidualne klucze wordpress API');
define('NONCE_SALT',       'Twoje indywidualne klucze wordpress API');
define('DISABLE_WP_CRON', true);
define('DISALLOW_FILE_EDIT', true);
define('WP_MEMORY_LIMIT','2048M');
define('WP_MAX_MEMORY_LIMIT','8192M');
define('WP_DEBUG', false);
define('WP_DEBUG_DISPLAY', false);
@ini_set('display_errors', 0 );
define('WP_DEFAULT_THEME', 'Nazwa twojego szablonu');
define('COMPRESS_CSS', false);
define('CONCATENATE_SCRIPTS', false);
define('COMPRESS_SCRIPTS', false);
define('ENFORCE_GZIP', true);
define( 'WP_ENVIRONMENT_TYPE', 'production');
if(! defined( 'ABSPATH' ) ) {	define( 'ABSPATH', __DIR__ . '/' );
} require_once ABSPATH . 'wp-settings.php';